### ISSUE TITLE
can't find libs folder

### ISSUE THREAD

**Issue by hh1318** [mmertama/QtKMLLib#1]
why can't find libs folder ?

**Comment by mmertama** [comment]
Please can you elaborate a bit: did your compilation failed? Which OS and Qt version?

What kind of error did you get?

**Comment by hh1318** [comment]
can't find libs folder because I didn't compile libkml and qtkmllib,  i compile libkml and qtkmllib use minGW64，compile kmltest use msvc2019，my qt version is 5.15.2, now i can't generate qtkml.lib and libkml.lib(msvc2019 compile has error, minGW64 is ok), what should i do?

**Comment by mmertama** [comment]
I havent looked the code in years and I confused with my qmake stuff. I made a quick port to Qt6 and CMake, it is still in the feature branch - it still has some issues to fix. You may try that as well. However Im not sure if Qt5 compliant anymore. 

Please see qt6 branch

Tested only on mac and qt6.5

**Comment by mmertama** [comment]
The changes are now in master.
